name: Build and Create Release
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
jobs:
  build-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
      - name: Install deps
        run: sudo apt install git build-essential clang-10 llvm-10 libelf-dev linux-headers-$(uname -r) zlib1g ca-certificates
      - name: Install cargo-bpf
        run: cargo install cargo-bpf --git https://github.com/redsift/redbpf.git
      - name: Build
        run: cargo build --release
      - name: Upload Release Asset
        if: startsWith(github.event.push.tags, 'v')
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
          file: target/release/ready-to-rabbit
          asset_name: ready-to-rabbit
          overwrite: true
