name: Build and Create Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}
      - name: Install deps
        run: sudo apt install git build-essential clang-10 llvm-10 libelf-dev linux-headers-$(uname -r) zlib1g ca-certificates
      - name: Install cargo-bpf
        run: cargo install cargo-bpf --git https://github.com/redsift/redbpf.git
      - name: Build
        working-directory: ready-the-rabbit
        run: cargo build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
