name: Create Release with Assets
on:
  push:
    tags:
      - 'v*'
jobs:
  build-release:
    timeout-minutes: 40
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('Cargo.lock') }}
      - name: Install deps
        run: sudo apt-get install -y git build-essential clang-10 llvm-10 libelf-dev linux-headers-$(uname -r) zlib1g
      - name: Install cargo-make
        run: |
          wget https://github.com/sagiegurari/cargo-make/releases/download/0.32.1/cargo-make-v0.32.1-x86_64-unknown-linux-musl.zip
          unzip cargo-make-v0.32.1-x86_64-unknown-linux-musl.zip
          mv cargo-make-v0.32.1-x86_64-unknown-linux-musl/cargo-make ~/.cargo/bin/
      - name: Build release
        run: cargo make release
      - name: Upload assets
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
          file: target/release/ready-to-rabbit
          asset_name: ready-to-rabbit
          overwrite: true
